# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0029_auto_20171002_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(11, 41, 31, 329025), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(11, 41, 31, 329025), verbose_name='Time Out'),
        ),
    ]
