# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 23:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0030_auto_20171003_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(19, 23, 26, 399503), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(19, 23, 26, 399503), verbose_name='Time Out'),
        ),
    ]
