# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0032_auto_20171113_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(23, 1, 22, 672335), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(23, 1, 22, 672364), verbose_name='Time Out'),
        ),
    ]
