# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0035_auto_20171121_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(17, 41, 50, 946622), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(17, 41, 50, 946651), verbose_name='Time Out'),
        ),
    ]
