# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0036_auto_20171201_2143'),
        ('clockin', '0036_auto_20171128_1741'),
    ]

    operations = [
    ]
