# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0037_merge_20171202_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(11, 7, 1, 964889), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(11, 7, 1, 964918), verbose_name='Time Out'),
        ),
    ]
