# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0038_auto_20171202_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(23, 54, 38, 178434), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(23, 54, 38, 178434), verbose_name='Time Out'),
        ),
    ]
